const SUCCESS_CODE = 200;
const CREATE_CODE = 201;
const NOT_CORRECT_DATA_ERROR_CODE = 400;
const NOT_CORRECT_DATA = 401;
const ACSSECC_ERROR_CODE = 403;
const NOT_FIND_ERROR_CODE = 404;
const CONFLICT_ERROR_CODE = 409;
const DEFAULT_ERROR_CODE = 500;

module.exports = {
  NOT_CORRECT_DATA_ERROR_CODE,
  NOT_FIND_ERROR_CODE,
  DEFAULT_ERROR_CODE,
  SUCCESS_CODE,
  CREATE_CODE,
  NOT_CORRECT_DATA,
  CONFLICT_ERROR_CODE,
  ACSSECC_ERROR_CODE,
};
