const NOT_CORRECT_DATA_ERROR_CODE = 400;
const NOT_FIND_ERROR_CODE = 404;
const DEFAULT_ERROR_CODE = 500;
const SUCCESS_CODE = 200;
const CREATE_CODE = 201;

module.exports = {
  NOT_CORRECT_DATA_ERROR_CODE,
  NOT_FIND_ERROR_CODE,
  DEFAULT_ERROR_CODE,
  SUCCESS_CODE,
  CREATE_CODE,
};
